//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Datas.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class asistenteEntities : DbContext
    {
        public asistenteEntities()
            : base("name=asistenteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_persona> tbl_persona { get; set; }
        public virtual DbSet<tbl_usuario> tbl_usuario { get; set; }
    
        public virtual int sp_register_user(string nombre, string apellidos, string telefono, string correo, string url_img, string usr, string psw, string facebook, string google, string mail, ObjectParameter ret)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellidosParameter = apellidos != null ?
                new ObjectParameter("apellidos", apellidos) :
                new ObjectParameter("apellidos", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var url_imgParameter = url_img != null ?
                new ObjectParameter("url_img", url_img) :
                new ObjectParameter("url_img", typeof(string));
    
            var usrParameter = usr != null ?
                new ObjectParameter("usr", usr) :
                new ObjectParameter("usr", typeof(string));
    
            var pswParameter = psw != null ?
                new ObjectParameter("psw", psw) :
                new ObjectParameter("psw", typeof(string));
    
            var facebookParameter = facebook != null ?
                new ObjectParameter("facebook", facebook) :
                new ObjectParameter("facebook", typeof(string));
    
            var googleParameter = google != null ?
                new ObjectParameter("google", google) :
                new ObjectParameter("google", typeof(string));
    
            var mailParameter = mail != null ?
                new ObjectParameter("mail", mail) :
                new ObjectParameter("mail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_register_user", nombreParameter, apellidosParameter, telefonoParameter, correoParameter, url_imgParameter, usrParameter, pswParameter, facebookParameter, googleParameter, mailParameter, ret);
        }
    }
}
