//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Datas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_usuario
    {
        public int id { get; set; }
        public int id_persona { get; set; }
        public string psw { get; set; }
        public string usr { get; set; }
        public string facebook { get; set; }
        public string google { get; set; }
        public string mail { get; set; }
        public string alter_pass { get; set; }
        public string recibe_notificaciones { get; set; }
    
        public virtual tbl_persona tbl_persona { get; set; }
    }
}
