//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Datas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_bitacora
    {
        public long id { get; set; }
        public string mensaje { get; set; }
        public System.DateTime fecha { get; set; }
        public int id_usuario { get; set; }
    
        public virtual tbl_usuario tbl_usuario { get; set; }
    }
}
